# Generated by Django 3.1.4 on 2021-01-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('work_as', models.CharField(max_length=20)),
                ('Experience_years', models.IntegerField()),
            ],
        ),
    ]
